({
  "blog_title": "Dinner in Amsterdam, lunch at Panama´s Jungle",
  "blog_article": "I did exactly the opposite. I had dinner in Panama, took KLM´s direct flight to Amsterdam and had dutch pancakes the next day near Amsterdam Central station. It was so easy, I´m still shocked at it.\nIt made me think a lot about what people travel for and what they consider &#8220;exotic&#8221;. Being from Panama, for me, cold is an exotic destination. Examples of exotic animals include (and are not limited to): sheeps, furry cows (or furry anything), lambs. Interesting architecture features include chimneys.\nSo I thought to myself, isn´t this interesting. While I can take a plane at night and be in cold weather the next morning eating pancakes, anyone in Amsterdam can do the same and be on a boat at the Gatun lake in the afternoon watching monkeys or hike at one of our 15 minute away national parks and stay that night in a World Heritage colonial city (Casco Viejo) and have great dinner at a plaza that night.\nTravelling before used to be this amazing journey for months on mule, horse, boat. And once there, wao, you had to work your way back. Now is so easy&#8230; just wait two hours in the airport, take a sleeping pill and wake up to your adventure the next morning!\n\n\n\n\n\n",
  "blog_link": "http://arcoproperties.com/en/dinner-in-amsterdam-lunch-at-panama%c2%b4s-jungle/",
  "blog_date": "2009-10-02T09:48:23-05:00",
  "published": true,
  "$date_type": "date",
  "$image_type": "image",
  "blog_image": "https://beta.hotelherrera.com/image-src/fit-in/640x480/dinner-in-amsterdam-lunch-at-panama%c2%b4s-jungle-2009-10-1.jpg",
  "blog_description": "I did exactly the opposite. I had dinner in Panama, took KLM´s direct flight to Amsterdam and had dutch pancakes the next day near Amsterdam Central station. It was so easy, I´m still shocked at it.\nIt made me think a lot about what people travel for and what they consider &#8220;exotic&#8221;. Being from Panama, for me, cold is an exotic destination. Examples of exotic animals include (and are not limited to): sheeps, furry cows (or furry anything), lambs. Interesting architecture features incl",
  "blog_page_slug": "dinner-in-amsterdam-lunch-at-panama%c2%b4s-jungle"
})