({
  "blog_title": "Opera: a new kid in Casco´s block",
  "blog_article": "The National Theatre in Casco Viejo (Panama) was inaugurated back in 1908 with opera (Aida, not sure if they used the elefants or not!) . But curiously there wasn´t  an opera scene while I was growing up in Panama. And I grew up within the arts as I used to dance with Panama´s National Ballet. I never saw opera. Not because my parents weren´t fans, as being Italian, my mother knew  all of Verdi´s operas by heart, and I have to say she sang it beautifully (while she thought no one was looking).\nThen I have to assume most art shows where focused on orchestra, chamber orchestras, ballet, dance in all forms, painting&#8230; anything, but opera.  Maybe language was a problem? who knows.  I do have fond memories of my first (and only) opera experience while dancing.  I most have been 14 years old, and Armando Villamil worked with Maestro Ledezma in putting together Carmina Burana for Panama´s National Orchestra´s 50th anniversary.  They did it at Panama´s biggest theatre (Atlapa) and public didn´t fill out not even the platea. However, for those who went, they had a wonderful time.\nFor me, it was a fantastic experience, for the first time ever we had everyone who was anything in Panama participating. Choruses, modern dance, ballet, they pulled people out of the univesities, schools, every aficionado and professional they could get their hands on. And I´m not kidding.  They even had musclebuilders to carry Fortune into the stage.  I was so impressed by these colossus creatures painted in gold&#8230; well, excited about them until one came shyly to me and asked&#8230; &#8220;sorry miss&#8230; this play is beautiful&#8230; what is it? Cleopatra?&#8221;&#8230;. oh well&#8230; my first encounter with the &#8220;brains vs muscle&#8221; theory&#8230; at least they asked and where interested! somehow I´ve never been able to see a muscle builder the same since then.\nBut back to the story&#8230; Most people in countries where opera is an stablished art they would think as it as something normal. But in Panama, the movement has been built almost grassroots, like an underground thing.  Young guys, almost rebels waving the flag of opera like missionaries trying to get people to go.  And they´ve been succeeding! their passion is bearing fruit.\nSo here it is! for the first time since 1908&#8230; the first Opera Festival in Panama! and it had to be &#8211; of course- in Casco Viejo, where it all began, and where everything has a chance to reinvent itself.\nBig note: the first 100 people to contact the association get free tickets!\nHERE IS THE INFO \n",
  "blog_link": "http://arcoproperties.com/en/opera-a-new-kid-in-casco%c2%b4s-block/",
  "blog_date": "2010-04-07T09:18:15-05:00",
  "published": true,
  "$date_type": "date",
  "$image_type": "image",
  "blog_image": "",
  "blog_description": "The National Theatre in Casco Viejo (Panama) was inaugurated back in 1908 with opera (Aida, not sure if they used the elefants or not!) . But curiously there wasn´t  an opera scene while I was growing up in Panama. And I grew up within the arts as I used to dance with Panama´s National Ballet. I never saw opera. Not because my parents weren´t fans, as being Italian, my mother knew  all of Verdi´s operas by heart, and I have to say she sang it beautifully (while she thought no one was looking).\nT",
  "blog_page_slug": "opera-a-new-kid-in-casco%c2%b4s-block"
})