({
  "blog_title": "Panama Art: Casco Antiguo residents in Brook Alfaro´s art",
  "blog_article": "Panama, Casco Viejo &#8211; Casco Antiguo, San Felipe\nBrook Alfaro painting of Woman From Chorrillo \nThe first time I met Brook Alfaro was at least ten years ago. He was recently moving into his apartment in Casco Viejo, and he was one of the first founders of Fundacion Calicanto, which at the time was fighting to include Casco Antiguo into UNESCO´s World Heritage Sites. It was probably also the first time I walked into a true artist´s studio. His apartment was very beautiful, but I didn´t really notice (until after, of course). What got me was his painting room, with the canvases on work. Color everywhere, as I have never seen before that time. I have always had this fascination with work &#8220;on the works&#8221; &#8230; what was it before it got completed. And on both ends &#8221; on the works&#8221; and &#8220;finished&#8221;, Brook´s paintings make an impact.\nHe´s themes where always very human, mostly inspired in the people of San Felipe, Santa Ana and Chorrillo. At some point, he decided to explore other media and went radically different: he went to digital and video. A part of me was dissapointed since I´m such a fan of his paintings, but another part of me said: &#8220;well, about time a good professional guy raised the bar in art video in Panama&#8221;. And he did, also exposing the raw parts of our society.\nAs a person, Brook can be overlooked, with his big eyes and curly white hair, you know he is in art but you are not quite sure in which one. His temperament is so mellow and relaxed that the last thing you can imagine is that he is the author of such hurricanes of painted (or filmed) emotions.\nYesterday, with great pleasure, I see him again in the cover of La Prensa´s &#8220;K&#8221; magazine. He is back into painting. Although he moved out of San Felipe (but still kept his apartment!), he never left it. His inspiration is still in the same spot, as it has proven to be so rich. This time, he is exploring portraits. He has come back with his classic combination of humor and intensity. Or just humor or just intensity. He might play either one or at the same time!\nWelcome back Brook, we missed you. And thanks for the good work!\n",
  "blog_link": "http://arcoproperties.com/en/panama-art-casco-antiguo-residents-in-brook-alfaro%c2%b4s-art/",
  "blog_date": "2008-09-05T13:16:51-05:00",
  "published": true,
  "$date_type": "date",
  "$image_type": "image",
  "blog_image": "",
  "blog_description": "Panama, Casco Viejo &#8211; Casco Antiguo, San Felipe\nBrook Alfaro painting of Woman From Chorrillo \nThe first time I met Brook Alfaro was at least ten years ago. He was recently moving into his apartment in Casco Viejo, and he was one of the first founders of Fundacion Calicanto, which at the time was fighting to include Casco Antiguo into UNESCO´s World Heritage Sites. It was probably also the first time I walked into a true artist´s studio. His apartment was very beautiful, but I didn´t reall",
  "blog_page_slug": "panama-art-casco-antiguo-residents-in-brook-alfaro%c2%b4s-art"
})