({
	display_title: 'Trabajos',
	published: true,
	$date_value: '2018-07-20',
	$date_type: 'date',
	date: 'Thursday, 20 July, 2018',
	$marked_markdown: true,
	$marked_type: 'textarea',
	marked: '# Encabezado 1\n## Encabezado 2\n### Encabezado 3\n#### Encabezado 4\n##### Encabezado 5\n###### Encabezado 6\n\nPárrafo.\n\n* Objeto 1;\n* artículo 2;\n* artículo 3.\n\nOtro párrafo.\n\n1 articulo;\n2. artículo;\n3. artículo.\n\nEl rápido y marrón \'zorro\' salta sobre un perro perezoso. DJs acuden cuando MTV ax cuestionario prog. La prueba de chatarra de MTV agraciada por las crías de zorro. Bawds trotar, flick cuarzo, vex ninfas.\n\n¡Vals, mala ninfa, para jigs rápidos vex! Las ninfas de los zorros agarran el vals rápido. Ladrillo de prueba whangs jumpy veldt `fox`. Las zorras brillantes saltan; Cuervo de aves caseras.\n\nQuick wafting zephyrs vex bold Jim. Rápido golpe de \'zephyrs`, molesto daft Jim. Fop cargado de sexo sopló mi prueba de televisión basura. ¿Qué tan rápido daft salta cebras vex. Dos deportistas impulsados ​​ayudan a enviar por fax mi gran cuestionario. Rápido, Baz, ¡consigue mis jodhpurs de lino tejidos! "Ahora, fax, prueba a Jack", mi valiente.\n\n[chat de enduro.js] (https://gitter.im/Enduro-js/Lobby)\n\n`` `\n<nav class = "aPagination">\n    {{# a menos que primero}}\n        <a href="{{prev_page}}" class="aPagination-aPrevious"> {{previous_page_label}} </a>\n    {{/a no ser que}}\n    {{# a menos que}}\n        <a href="{{next_page}}" class="aPagination-aNext"> {{next_page_label}} </a>\n    {{/a no ser que}}\n    <div style = "clear: both;"> </div>\n</nav> `` `\n\n¡Vals, mala ninfa, para jigs rápidos vex! Las ninfas de los \n\nzorros agarran el vals rápido. Ladrillo de prueba whangs jumpy veldt `fox`. Las zorras brillantes saltan; Cuervo de aves caseras.\nSend feedback',
	$marked_en: '# Header 1\n## Header 2\n### Header 3\n#### Header 4\n##### Header 5\n###### Header 6\n\nParagraph.\n\n* Item 1;\n* item 2;\n* item 3.\n\nAnother paragraph.\n\n1. Item;\n2. item;\n3. item.\n\nThe quick, brown `fox` jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by `fox` whelps. Bawds jog, flick quartz, vex nymphs.\n\nWaltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt `fox`. Bright vixens jump; dozy fowl quack.\n\nQuick wafting zephyrs vex bold Jim. Quick `zephyrs` blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack! " my brave.\n\n[enduro.js chat](https://gitter.im/Enduro-js/Lobby)\n\n```\n<nav class="aPagination">\n    {{#unless first}}\n        <a href="{{prev_page}}" class="aPagination-aPrevious">{{previous_page_label}}</a>\n    {{/unless}}\n    {{#unless last}}\n        <a href="{{next_page}}" class="aPagination-aNext">{{next_page_label}}</a>\n    {{/unless}}\n    <div style="clear: both;"></div>\n</nav>```\n\nWaltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt `fox`. Bright vixens jump; dozy fowl quack.'
})