service: uppyloader

provider:
  name: aws
  runtime: nodejs8.10

  environment:
    # NOTE: Make sure you set this to the url of your service endpoint
    DOMAIN: admin.hotelherrera.com 
    COMPANION_OAUTH_DOMAIN: www.hotelherrera.com
# corresponds to the server.validHosts option
    COMPANION_DOMAINS: hotelherrera.com, www.hotelherrera.com

# corresponds to the sendSelfEndpoint option
    COMPANION_SELF_ENDPOINT: www.hotelherrera.com/Bla

# comma-separated URLs
# corresponds to the uploadUrls option
    COMPANION_UPLOAD_URLS: http://www.hotelherrera.com/files/
    
    # NOTE: Make sure you set the API Keys for your chosen provider

    AWS_S3_BUCKET: hotel-herrera
    AWS_S3_REGION: us-east-1 
    AWS_S3_KEY: AKIAY3QWPMGHF2GRXDMJ 
    AWS_S3_SECRET: bFRxeGsHCsT4uzh4oCqe7hDLVp4qhRJd6m0rjSYt

    SESSION_SECRET: rjpP7essLSuWpeQt2h76j36m 

    UPPY_SECRET: rjpP7essLSuWpeQt2h76j36m 

    # INSTAGRAM_KEY: <YOUR_INSTAGRAM_KEY>
    # INSTAGRAM_SECRET: <YOUR_INSTAGRAM_SECRET>

    # GOOGLE_KEY: <YOUR_GOOGLE_KEY>
    # GOOGLE_SECRET: <YOUR_GOOGLE_SECRET>

    DROPBOX_KEY: ffno53h4fug37yg 
    DROPBOX_SECRET: hxnvwqqwcuex3fp

functions:
  uppy:
    handler: index.uppy

    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
